apiVersion: v1
kind: Service
metadata:
  name: upf-embb-shaper
  namespace: 5gs
spec:
  selector:
    app.kubernetes.io/name: upf
    app.kubernetes.io/instance: open5gs
  ports:
    - {port: 8081, targetPort: shaper-api, name: api}
